### PR TITLE
add the module class

### PR DESCRIPTION
**Pull request by alexlieu**
Left 2 of the methods empty as I think it would be better to come back to them. Please have a looksies

### CODE REVIEW

**Review by JCanning1 — CHANGES_REQUESTED** [review]
It's probably best to declare res outside the try-catch block with pstmt, and then close them both in the finally block with if(res != null) res.close(); etc.
That way res and pstmt still close if something goes wrong.

**Review by tomsnowgb — APPROVED** [review]
Looks good, concur with Jamie.

**Review by JCanning1 — CHANGES_REQUESTED** [review]
Module looks good, User needs the ResultSets closing @tomsnowgb .

**Comment by tomsnowgb** [comment]
> Module looks good, User needs the ResultSets closing @tomsnowgb .

Done x

**Pull request merged**
